name: Alerts Purger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'