name: Test OpsGenie Actions

on:
  workflow_dispatch:
    inputs:
      create-alert-branch:
        description: 'Branch for Create OpsGenie Alert'
        required: false
        default: 'main'
      close-alert-branch:
        description: 'Branch for Close OpsGenie Alert'
        required: false
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set alert alias
        run: |
          export ALIAS=test-alert-$(date +%s)
          echo "ALERT_ALIAS=$(echo -n $ALIAS)" >> $GITHUB_ENV

      - name: Create OpsGenie Alert
        uses: ${{ format('rockem/create-opsgenie-alert-action@{0}', github.event.inputs.create-alert-branch) }}
        with:
          api_key: ${{ secrets.OPSGENIE_API_KEY }}
          alias: ${{ env.ALERT_ALIAS }}
          message: >
            OpsGenie actions test
          priority: P5
          tags: e2e, test, actions

      - name: Give alert time to be created
        run: sleep 2

      - name: Close OpsGenie Alert
        uses: ${{ format('rockem/close-opsgenie-alert-action@{0}', github.event.inputs.close-alert-branch) }}
        with:
          api_key: ${{ secrets.OPSGENIE_API_KEY }}
          alias: ${{ env.ALERT_ALIAS }}
          user: kuku@gmail.com
          note: Closing test alert

      - name: Give alert time to close
        run: sleep 2

      - name: Verify alert exists and closed
        env:
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
        run: node .github/workflows/assert_closed_alert_exists.js $ALERT_ALIAS
