name: Test OpsGenie Actions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 0 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn

      - name: Set alert alias
        run: |
          export ALIAS=test-alert-$(date +%s)
          echo "ALERT_ALIAS=$(echo -n $ALIAS)" >> $GITHUB_ENV

      - name: Create OpsGenie Alert
        uses: rockem/create-opsgenie-alert-action@v1
        with:
          api_key: ${{ secrets.OPSGENIE_API_KEY }}
          alias: ${{ env.ALERT_ALIAS }}
          message: >
            OpsGenie actions test
          priority: P5

      - name: Give alert time to be created
        run: sleep 2

      - name: Close OpsGenie Alert
        uses: rockem/close-opsgenie-alert-action@v1
        with:
          api_key: ${{ secrets.OPSGENIE_API_KEY }}
          alias: ${{ env.ALERT_ALIAS }}

      - name: Give alert time to close
        run: sleep 2

      - name: Verify alert is closed
        env:
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
        run: node ./src/assert_closed_alert_exists.js $ALERT_ALIAS
